accounts/urls.py
from django.conf.urls import url
from accounts import views


from .views import (
    login_view,
    register_view,
    logout_view,
)
from django.contrib.auth.views import password_reset, password_reset_done


urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    # url(r'^change-password/$', views.change_password, name='change_password'),
    # url(r'reset-password/$', password_reset, name='reset_password'),
    # url(r'reset-password/done/$', password_reset_done, name='password_reset_done'),
    # url(r'^password/$', views.change_password, name='change_password'),
]

bankingsystem/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about, transfer, index, change_password, transfer_pin, transfer_auth, loginsuccessful, \
    account_summary


urlpatterns = [
    # admin
    url(r'^admin/', admin.site.urls),
    # Accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    url(r'^transfer.html/$', transfer, name='transfer'),
    url(r'^index.html/$', index, name='index'),

    url(r'^change_password.html/$', change_password, name='change_password'),
    url(r'^transfer_pin.html/$', transfer_pin, name='transfer_pin'),
    url(r'^transfer_auth.html/$', transfer_auth, name='transfer_auth'),
    url(r'^loginsuccessful.html/$', loginsuccessful, name='loginsuccessful'),
    url(r'^account_summary.html/$', account_summary, name='account_summary'),

    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.conf.urls import url

from .views import deposit_view, withdrawal_view

urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^deposit/$', deposit_view, name='deposit'),
    url(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    username = models.CharField(
        _('username'), max_length=30, unique=True, null=True, blank=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters, digits and '
            '@/./+/-/_ only.'
        ),
        validators=[
            RegexValidator(
                r'^[\w.@+-]+$',
                _('Enter a valid username. '
                    'This value may contain only letters, numbers '
                    'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })

    email = models.EmailField(unique=True, null=False, blank=False)
    contact_no = models.IntegerField(unique=True, blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def account_no(self):
        if hasattr(self, 'account'):
            return self.account.account_no
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.city,
                self.address.postal_code,
                self.address.country,
            )
        return None


class AccountDetails(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_no = models.PositiveIntegerField(
        unique=True,
        validators=[
            MinValueValidator(10000000),
            MaxValueValidator(99999999)
        ]
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(null=True, blank=True)
    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )
    picture = models.ImageField(
        null=True,
        blank=True,
        upload_to='account_pictures/',
    )

    def __str__(self):
        return str(self.account_no)


class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


from transactions.models import Diposit, Withdrawal, Interest, Transfer_fund



def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})

    else:
        user = request.user
        deposit = Diposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']
        transfer_fund = Transfer_fund.objects.filter(user=user)

        context = {
                    "user": user,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "interest": interest,
                    "interest_sum": interest_sum,
                    "transfer_fund": transfer_fund,
                  }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})



def transfer(request):
    return render(request, "core/transfer.html", {})

def index(request):
    return render(request, "core/index.html", {})

def transfer_pin(request):
    return render(request, "core/transfer_pin.html", {})

def account_summary(request):
    return render(request, "core/account_summary.html", {})

def transfer_auth(request):
    return render(request, "core/transfer_auth.html", {})

def loginsuccessful(request):
    return render(request, "core/loginsuccessful.html", {})






@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'core/change_password.html', {
        'form': form
    })

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}

<h1>About US</h1>
<hr>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Why do we use it?</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
</p>


<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>

{% endblock content %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <!--<head>-->
    <!--<meta charset="utf-8">-->
    <!--<meta http-equiv="X-UA-Compatible" content="IE=edge">-->
    <!--<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
    <!--&lt;!&ndash; The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags &ndash;&gt;-->
    <!--<title>{% block title %} Lagos Bank {% endblock title %}</title>-->
    <!--<LINK href="css/styles.css" type=text/css rel=stylesheet>-->


    <!--&lt;!&ndash; Bootstrap &ndash;&gt;-->
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
  <!--</head>-->


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Home</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans&display=swap" rel="stylesheet">
<!---->
    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/73e4a67fd5.js"></script>

    <!-- date picker css -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
     <!--<a href="https://github.com/eternicode/bootstrap-datepicker">eternicode bootstrap-datepicker</a>-->
    <!-- Our Custom CSS -->
    <!--<link rel="stylesheet" href="{% static 't/style.css'%}">-->
    <link rel="stylesheet" href="{% static 't/loginform.css'%}">

<!--</head>-->



  <body>
{% include "core/navbar.html" %}

<div class="container" style="padding-top: 60px;">
{% block content %}

{% endblock content %}
</div>
{% include "core/footer.html" %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  </body>
</html>

core/templates/core/change_password.html
{% load crispy_forms_tags %}{% load static %}



<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Transfer</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans&display=swap" rel="stylesheet">

    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/73e4a67fd5.js"></script>

    <!-- date picker css -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
    <!-- <a href="https://github.com/eternicode/bootstrap-datepicker">eternicode bootstrap-datepicker</a> -->
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 't/style.css'%}">
    <link rel="stylesheet" href="{% static 't/loginform.css'%}">

  </head>
{% block content %}

<body>

    <header>
        <div id="content1">
            <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
                <div class="container-fluid">
                    <img src="{% static '/t/img/logo.png'%}" alt="Logo">
                    <h3>Logo</h3>
                </div>
            </nav>
        </div>
    </header>


<div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/architecture.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; height: 700px">

<!--<section class="container" style="padding: 000px 300px 000px">-->
        <div class="row" style="padding-top: 100px ">
            <div class="col-md-12">
                <!--<div class="card pt-1">-->
                    <div class="card-body" style="-moz-box-shadow: 1px 1px 3px 5px #0063b1;
  -webkit-box-shadow: 1px 1px 3px 2px #0063b1;
  box-shadow:         1px 1px 3px 3px #40ea43;">

                        <h3 align="center">{{ title }}</h3><hr>
                        <form class="" method="POST" action="" >
                             <div class="col-sm-4" >
                               <div>
                                {% csrf_token %}
                                 {{ form|crispy }}
                             <input class="btn btn-primary btn-md" type="submit" value='Save Changes'>
                                 <!--<div class="">Not a member?   <a href="{% static 't/name.pdf'%}">Open Account</a></div>-->

                                 <!--<a class="btn btn-success btn-md" href="{% static 't/name.pdf'%}" role="button">Register</a>-->
                             </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

</div>
    </body>

<!--<form method="post">-->
  <!--{% csrf_token %}-->
  <!--{{ form }}-->
  <!--<button type="submit">Save changes</button>-->
<!--</form>-->
{% endblock content %}

core/templates/core/index.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include "core/messages.html" %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Home</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans&display=swap" rel="stylesheet">
<!---->
    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/73e4a67fd5.js"></script>

    <!-- date picker css -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
     <!--<a href="https://github.com/eternicode/bootstrap-datepicker">eternicode bootstrap-datepicker</a>-->
    <!-- Our Custom CSS -->
    <!--<link rel="stylesheet" href="{% static 't/style.css'%}">-->
    <link rel="stylesheet" href="{% static 't/loginform.css'%}">

<!--</head>-->

<div>

    <header>
        <div id="content1">
            <nav class="navbar navbar-expand-lg  fixed-top" style="background-color: white">
                <!--<div class="container-fluid">-->
                    <!--<div class="p-3 mb-2 ">.bg-primary</div>-->
                    <img src="{% static '/t/img/logo.png'%}" alt="Bales Bank">
                    <!--<h3>Bales Bank</h3>-->
                </div>
            </nav>
        </div>
    </header>

<div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/architecture.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; height: 650px">




<section class="container">
        <div class="row" style="padding: 200px 200px 200px !important">
            <div class="col-md-12>
                <div class="card pt-4">
                    <div class="card-body">
                        <br class="lead text-muted"><br><strong>Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</strong></br></p>
        <p>
          <a class="btn btn-primary btn-md" href="{% url 'accounts:login' %}" role="button">Load Account Details</a>
          <a class="btn btn-success btn-md" href="{% static 't/name.pdf'%}" role="button">Register</a>
          <!--<a class="btn btn-success btn-md" href="{% url 'accounts:register' %}" role="button">Create a Bank Account</a>-->
        </p>

                    </div>
                </div>

</div>
</section>

            <!--<div class="col-md-6 split right">-->
                <!--<figure>-->
                    <!--<img src="{% static 't/img/bank 3.jpg'%}" alt="" style="width: 700px; height: 650px">-->
                <!--</figure>-->
            <!--</div>-->
        <!--</div>-->





<!--<section class="container">-->
    <!--<div class ="row" style=" padding-top:100px ! important;">-->
<!--<div class="container" style="padding-top: 50px;">-->
<!--<div class="jumbotron text-center">-->
      <!--<div class="container">-->
        <!--<h1 class="jumbotron-heading">Online Banking</h1>-->
        <!--<hr>-->
        <!--<p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>-->
        <!--<p>-->
          <!--<a class="btn btn-primary btn-md" href="{% url 'accounts:login' %}" role="button">Load Account Details</a>-->
          <!--<a class="btn btn-success btn-md" href="{% static 't/name.pdf'%}" role="button">Register</a>-->
          <!--&lt;!&ndash;<a class="btn btn-success btn-md" href="{% url 'accounts:register' %}" role="button">Create a Bank Account</a>&ndash;&gt;-->
        <!--</p>-->
      <!--</div>-->

<!--</div>-->
<!--</div>-->
        <!--</div>-->
<!--</section>-->

</div>
</section>
</body>
{% endblock content %}

core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

core/templates/core/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}"><img src ="{%static 'media/logo.png'%}"/>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!--<div class="collapse navbar-collapse" id="navbarSupportedContent">-->
    <!--<ul class="navbar-nav mr-auto">-->
      <!--<li class="nav-item active">-->
        <!--<a class="nav-link" href="{% url 'home' %}">Home</a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="{% url 'about' %}">About Us</a>-->
      <!--</li>-->

    <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="{% url 'transfer' %}">Transfer Funds</a>-->
    <!--</li>-->
    <!--</ul>-->
    <form class="form-inline my-2 my-lg-0">
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger btn-sm" type="button">Logout</a>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-success btn-sm" type="button">Load Account Details</a> |
            <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-sm" type="button">Create an Account</a>
        {% endif %}
    </form>
  </div>
</nav>

core/templates/core/transactions_original.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% load static %}
{% block content %}
{% include "core/messages.html" %}
<nav class="navbar navbar-white bg-white justify-content-between" xmlns:margin="http://www.w3.org/1999/xhtml"
     xmlns:margin="http://www.w3.org/1999/xhtml">
    <a class="navbar-brand">Personal Banking</a>
    <span class="navbar-text">
    Secured Site
  </span>

</nav>
<div style="padding-left:0px;" width="50">
    <div class="page-header">
        <!--<h1 class="text-center" style="color:white;" ><b>Lagos Bank</b><br><small>Lagos Bank Ltd.</small></h1>-->
        <img src ="{{user.account.picture.url}}" width="110" height="150">
    </div>

    <div class="row">

        <div class="col-xs-3 col-md-8 text-left">
            <h4><b>Account Name: </b>{{ user.full_name }}</h4>
            <h4><b>Date of Birth: </b>{{ user.account.birth_date }}</h4>
            <h4><b>Gender: </b>{{ user.account.get_gender_display }}</h4>
            <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
            <h4><b>Email Address: </b>{{ user.email }}</h4>
            <h4><b>Address: </b>{{ user.full_address }}</h4>

        </div>
        <div class="col-xs-6 col-md-4 text-left">
            <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
            <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
            <div class="well">
                <h4 class="card"><b>Account Balance: </b>{{ user.balance }} $</h4>
                <!--<a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>-->
                <!--<a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>-->
                <a class ="btn btn-danger" href="{% url 'index' %}">Transfer</a>
            </div>
        </div>

    </div>

    <hr>
    <div class="page-header" >
        <h2 class="text-center"><b>Transaction Details</b></h2>
        <div>

            <div class="col-xs-4 col-md-6" style="background-color:grey; margin: 0px 200px; padding:30px" >
                <h3>Deposit Details</h3>
                <table class="table table-hover table-bordered" >
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Date / Time</th>
                        <th>Details</th>
                        <th>Amount ($)</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% for obj in deposit %}
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{ obj.timestamp }}</td>
                        <td>Deposit</td>
                        <td>{{ obj.amount }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th class="text-right" scope="row" colspan="3">Total</th>

                        <td>{{ deposit_sum }}</td>
                    </tr>

                    </tbody>
                </table>
                <hr>


                <h3>Withdrawal Details</h3>
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Date / Time</th>
                        <th>Details</th>
                        <th>Amount ($)</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% for obj in withdrawal %}
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{ obj.timestamp }}</td>
                        <td>Withdrawal</td>
                        <td>{{ obj.amount }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th class="text-right" scope="row" colspan="3">Total</th>

                        <td>{{ withdrawal_sum }}</td>
                    </tr>

                    </tbody>
                </table>
                <hr>


                <h3>Interest Details</h3>
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Date / Time</th>
                        <th>Details</th>
                        <th>Amount ($)</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% for obj in interest %}
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{ obj.timestamp }}</td>
                        <td>Interest</td>
                        <td>{{ obj.amount }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th class="text-right" scope="row" colspan="3">Total</th>

                        <td>{{ interest_sum }}</td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <hr>






    {% endblock content %}